### ISSUE TITLE
trying to get working issues with Missing Native

### ISSUE THREAD

**Issue by Bucky420** [arthurdead/sm_npcs#2]
im testing the mvm plugin and .. i get 
```
EntityFactoryDictionary.register_function
CustomSendtable.from_factory
```
 when i load tryed diffrent versions and stuff but yea. any help would be nice.

just wanted to use this as a refrance but i just wanted to fix the tf2 Engy on ctf LOL if i can get him to move it would make my day

**Comment by arthurdead** [comment]
this repo only has testing/outdated/incomplete stuff
